module.exports = {
  future: { purgeLayersByDefault: true },
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        'primary': 'var(--primary)',
        'secondary': 'var(--secondary)',
        'third': 'var(--third)',
        'hover': 'var(--hover)',
        'hover-1': 'var(--hover-1)',
        'hover-2': 'var(--hover-2)',
        'accents-0': 'var(--accents-0)',
        'accents-1': 'var(--accents-1)',
        'accents-2': 'var(--accents-2)',
        'accents-3': 'var(--accents-3)',
        'accents-4': 'var(--accents-4)',
        'accents-5': 'var(--accents-5)',
        'accents-6': 'var(--accents-6)',
        'accents-7': 'var(--accents-7)',
        'accents-8': 'var(--accents-8)',
        'accents-9': 'var(--accents-9)',
        'violet': 'var(--violet)',
        'violet-light': 'var(--violet-light)',
        'pink': 'var(--pink)',
        'cyan': 'var(--cyan)',
        'blue': 'var(--blue)',
        'green': 'var(--green)',
        'red': 'var(--red)',
      },
      textColor: {
        base: 'var(--text-base)',
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
      },
      lineHeight: { 'extra-loose': '2.2' }
    },
  },
  variants: {},
  plugins: [],
};